spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: ${DATABASE_USERNAME} # 환경변수에 설정함 DATABASE_USERNAME=root;
    password: ${DATABASE_PASSWORD} # 환경변수에 설정함 DATABASE_PASSWORD= *****;
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://project-1.c5mic2ksgw7b.ap-northeast-2.rds.amazonaws.com:3306/innodb?useUnicode=true&characterEncoding=utf8mb4

server:
  port: 8080

logging:
  config: classpath:logback-spring-prod.xml
